apiVersion: v2
name: order-service
description: A Helm chart for the Order Service in the E-Commerce Platform
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 12.1.0
    repository: https://charts.bitnami.com/bitnami