replicaCount: 1

image:
  repository: my-ecommerce/notification-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: notification-service.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []