apiVersion: v2
name: product-service
description: A Helm chart for the Product Service microservice in the E-Commerce platform
type: application
version: 0.1.0
appVersion: "1.0.0"

maintainers:
  - name: YourName
    email: your.email@example.com

dependencies: []