name: Build & Push Microservices

on:
  push:
    branches: [main]
    paths:
      - '**/Dockerfile'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - write-db-service
          - producer-service
          - product-service
          - consumer-service
          - payment-service
          - gateway
          - inventory-service
          - notification-service
          - redis-service
          - order-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set lowercase IMAGE_OWNER
      run: echo "IMAGE_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push ${{ matrix.service }}
      run: |
        docker build -t $REGISTRY/${IMAGE_OWNER_LC}/${{ matrix.service }}:latest \
          -f ${{ matrix.service }}/Dockerfile .
        docker push $REGISTRY/${IMAGE_OWNER_LC}/${{ matrix.service }}:latest
